name: Build, Run & Deploy

on:
  schedule:
    - cron: "0 23 * * *" # Runs at 9am (daylight savings or 10 am non-daylight savings)
  workflow_dispatch: 

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Rust Build & Run
      uses: actions/checkout@v2
    - name: Make env
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_ORG_KEY: ${{ secrets.ORG_KEY }}
        envkey_DW_KEY: ${{ secrets.DW_KEY }}
        envkey_AWS_ORG_KEY: ${{ secrets.AWS_ORG_KEY }}
    - run: sudo timedatectl set-timezone Australia/Sydney
    - run: cargo run
    - name: Make PDF Report
      uses: xu-cheng/latex-action@v2
      with:
        working_directory: report/src
        root_file: report.tex
    - name: Upload PDF Report
      uses: actions/upload-artifact@v2
      with:
        name: clyde-water-quality-report.pdf 
        path: report/src/report.pdf
    - name: Deploy GH Pages
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: page # The folder the action should deploy.
