name: Run & Deploy

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 23 * * *" # Runs at 9am (daylight savings or 10 am non-daylight savings)
  workflow_dispatch: 

env:
  CARGO_TERM_COLOR: always

jobs:
  build_rust:
    runs-on: ubuntu-latest
    steps:
    - name: Build & Run
      uses: actions/checkout@v2
    - name: Make env
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_ORG_KEY: ${{ secrets.ORG_KEY }}
        envkey_DW_KEY: ${{ secrets.DW_KEY }}
        envkey_AWS_ORG_KEY: ${{ secrets.AWS_ORG_KEY }}
    - run: cargo run
      
  build_latex:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: xu-cheng/latex-action@v2
        with:
          working_directory: report/src
          root_file: report.tex
      - uses: actions/upload-artifact@v2
        with:
          name: clyde-water-quality-report.pdf 
          path: report/src/report.pdf
